# commands
#build test on local machine : docker build -f Dockerfile.test -t splitshare-test .
# run test on local machine : docker run --rm splitshare-test

# Test-only Dockerfile
FROM maven:3.9.6-eclipse-temurin-17

# Install Tesseract and required data files
RUN apt-get update && apt-get install -y tesseract-ocr wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/share/tessdata && \
    wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -P /usr/share/tessdata && \
    wget https://github.com/tesseract-ocr/tessdata/raw/main/osd.traineddata -P /usr/share/tessdata

ENV TESSDATA_PREFIX=/usr/share/

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src

CMD ["mvn", "test"]
